services:
  rabbit:
    image: rabbitmq:4.2-rc-management
    hostname: rabbit
    restart: always
    container_name: rabbit
    environment:
      RABBITMQ_ERLANG_COOKIE: SWQOKODSQALRPCLNMEQG
      RABBITMQ_DEFAULT_USER: metrical
      RABBITMQ_DEFAULT_PASS: metrical2025
      RABBITMQ_DEFAULT_VHOST: /
    ports:
      - '15672:15672'
      - '5672:5672'
    labels:
      NAME: rabbitmq
    networks:
      metrical_network:
        ipv4_address: 152.18.0.13

networks:
  metrical_network:
    external:
      name: metrical_network